apiVersion: apps/v1
kind: Deployment
metadata:
  name: clock-stopwatch-deployment
spec:
  replicas: 2  # Number of desired replicas
  selector:
    matchLabels:
      app: clock-stopwatch
  template:
    metadata:
      labels:
        app: clock-stopwatch
    spec:
      containers:
      - name: clock-stopwatch
        image: rameshkumarverma/clock-stopwatch
        ports:
        - containerPort: 80
