apiVersion: apps/v1
kind: Deployment
metadata:
  name: compound-interest-calculator-deployment
spec:
  replicas: 2  # Number of desired replicas
  selector:
    matchLabels:
      app: compound-interest-calculator
  template:
    metadata:
      labels:
        app: compound-interest-calculator
    spec:
      containers:
      - name: compound-interest-calculator
        image: rameshkumarverma/compound-interest-calculator
        ports:
        - containerPort: 80
