apiVersion: apps/v1
kind: Deployment
metadata:
  name: week-day-predictor-app-deployment
spec:
  replicas: 2  # Number of desired replicas
  selector:
    matchLabels:
      app: week-day-predictor-app
  template:
    metadata:
      labels:
        app: week-day-predictor-app
    spec:
      containers:
      - name: week-day-predictor-app
        image: rameshkumarverma/week-day-predictor-app
        ports:
        - containerPort: 80
