apiVersion: apps/v1
kind: Deployment
metadata:
  name: dicegame-deployment
spec:
  replicas: 2  # Number of desired replicas
  selector:
    matchLabels:
      app: dicegame
  template:
    metadata:
      labels:
        app: dicegame
    spec:
      containers:
      - name: dicegame
        image: rameshkumarverma/dicegame
        ports:
        - containerPort: 80
