apiVersion: apps/v1
kind: Deployment
metadata:
  name: white-board-deployment
spec:
  replicas: 2  # Number of desired replicas
  selector:
    matchLabels:
      app: white-board
  template:
    metadata:
      labels:
        app: white-board
    spec:
      containers:
      - name: white-board
        image: rameshkumarverma/white-board
        ports:
        - containerPort: 80
