apiVersion: apps/v1
kind: Deployment
metadata:
  name: classroom-scheduler-website-deployment
spec:
  replicas: 2  # Number of desired replicas
  selector:
    matchLabels:
      app: classroom-scheduler-website
  template:
    metadata:
      labels:
        app: classroom-scheduler-website
    spec:
      containers:
      - name: classroom-scheduler-website
        image: rameshkumarverma/classroom-scheduler-website
        ports:
        - containerPort: 80
