apiVersion: apps/v1
kind: Deployment
metadata:
  name: clock-deployment
spec:
  replicas: 2  # Number of desired replicas
  selector:
    matchLabels:
      app: clock
  template:
    metadata:
      labels:
        app: clock
    spec:
      containers:
      - name: clock
        image: rameshkumarverma/clock
        ports:
        - containerPort: 80
