pipeline{
    agent any
    // tools{
    //     jdk 'jdk17'
    //     nodejs 'node16'
    // }
    environment {
        SCANNER_HOME=tool 'sonar-scanner'
    }
    stages {
        stage('clean workspace'){
            steps{
                cleanWs()
            }
        }
        stage('Checkout from Git'){
            steps{
                git branch: 'main', url: 'https://github.com/rameshkumarvermagithub/Web-dev-projects.git'
            }
        }
        stage("Sonarqube Analysis "){
            steps{
              dir('CSS_loading-Animation-D-vers-1') {
                withSonarQubeEnv('sonar-server') {
                    sh ''' $SCANNER_HOME/bin/sonar-scanner -Dsonar.projectName=css-loading-animation-d-vers-1 \
                    -Dsonar.projectKey=css-loading-animation-d-vers-1'''
                }
              }
            }
        }
        stage("quality gate"){
           steps {
                script {
                  dir('CSS_loading-Animation-D-vers-1') {
                    waitForQualityGate abortPipeline: false, credentialsId: 'sonar'
                }
                }
            }
        }
        // stage('Install Dependencies') {
        //     steps {
        //         sh "npm install"
        //     }
        // }
        stage('OWASP FS SCAN') {
            steps {
              dir('CSS_loading-Animation-D-vers-1') {
                dependencyCheck additionalArguments: '--scan ./ --disableYarnAudit --disableNodeAudit', odcInstallation: 'DP-Check'
                dependencyCheckPublisher pattern: '**/dependency-check-report.xml'
            }
            }
        }
         stage('TRIVY FS SCAN') {
            steps {
              dir('CSS_loading-Animation-D-vers-1') {
                sh "trivy fs . > trivyfs.txt"
            }
            }
        }
        stage("Docker Build & Push"){
            steps{
                script{
                  dir('CSS_loading-Animation-D-vers-1') {
                   withDockerRegistry(credentialsId: 'docker', toolName: 'docker'){
                       sh "docker build -t rameshkumarverma/css-loading-animation-d-vers-1 ."
                       // sh "docker tag css-loading-animation-d-vers-1 rameshkumarverma/css-loading-animation-d-vers-1:latest"
                       sh "docker push rameshkumarverma/css-loading-animation-d-vers-1:latest"
                    }
                  }
                }
            }
        }
        stage("TRIVY"){
            steps{
              dir('CSS_loading-Animation-D-vers-1') {
                sh "trivy image rameshkumarverma/css-loading-animation-d-vers-1:latest > trivyimage.txt"
            }
            }
        }
        stage("deploy_docker"){
            steps{
              dir('CSS_loading-Animation-D-vers-1') {
                sh "docker stop css-loading-animation-d-vers-1 || true"  // Stop the container if it's running, ignore errors
                sh "docker rm css-loading-animation-d-vers-1 || true" 
                sh "docker run -d --name css-loading-animation-d-vers-1 -p 8080:80 rameshkumarverma/css-loading-animation-d-vers-1"
            }
            }
        }
      stage('Deploy to Kubernetes') {
            steps {
                script {
                    dir('CSS_loading-Animation-D-vers-1') {
                        withKubeConfig(caCertificate: '', clusterName: '', contextName: '', credentialsId: 'k8s', namespace: '', restrictKubeConfigAccess: false, serverUrl: '') {
                            // Apply deployment and service YAML files
                            sh 'kubectl apply -f deployment.yml'
                            sh 'kubectl apply -f service.yml'

                            // Get the external IP or hostname of the service
                            // def externalIP = sh(script: 'kubectl get svc amazon-service -o jsonpath="{.status.loadBalancer.ingress[0].hostname}"', returnStdout: true).trim()

                            // Print the URL in the Jenkins build log
                            // echo "Service URL: http://${externalIP}/"
                        }
                    }
                }
            }
        }

    }
}
