apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-guessor-deployment
spec:
  replicas: 2  # Number of desired replicas
  selector:
    matchLabels:
      app: color-guessor
  template:
    metadata:
      labels:
        app: color-guessor
    spec:
      containers:
      - name: color-guessor
        image: rameshkumarverma/color-guessor
        ports:
        - containerPort: 80
